---

- name: Install asdf-vm
  git: 
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: "{{ asdf_version }}"

- name: List plugins
  shell: |
    asdf plugin list
  register: asdf_plugin_list

- name: Install some runtimes with asdf-vm
  shell: |
    asdf plugin add {{ item }}
  when: asdf_plugin_list.stdout.find(item) == -1
  with_items: "{{ asdf_plugins }}"