---
- name: Install asdf-vm
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: "{{ asdf_version }}"

- name: Install asdf-vm dependencies (only RedHat)
  yum:
    name: jq
  when: ansible_facts['os_family'] == "RedHat" and ansible_distribution_major_version == '7'
  become: true

- name: List plugins
  shell: |
    source ~/.config/zsh/.zshrc
    asdf plugin list 2> /dev/null
    echo ''
  args:
    executable: /bin/zsh
  register: asdf_plugin_list
  changed_when: false

- name: Install some runtimes with asdf-vm
  shell: |
    source ~/.config/zsh/.zshrc
    asdf plugin add {{ item.name }} && {{ item.post_add|default('echo "post-add command is nothing"') }}
  args:
    executable: /bin/zsh
  when: asdf_plugin_list.stdout.find(item.name) == -1
  with_items: "{{ asdf_plugins }}"

- name: Update runtimes with asdf-vm
  shell: |
    source ~/.config/zsh/.zshrc
    asdf plugin update {{ item.name }}
  args:
    executable: /bin/zsh
  when: asdf_plugin_list.stdout.find(item.name) != -1
  with_items: "{{ asdf_plugins }}"


- name: Install package with asdf-vm
  shell: |
    source ~/.config/zsh/.zshrc
    asdf install {{ item.name }} {{ item.version }}
    asdf global {{ item.name }} {{ item.version }} && {{ item.post_install|default('echo "post-install command is nothing"') }}
  args:
    executable: /bin/zsh
  when: item.version is defined
  with_items: "{{ asdf_plugins }}"
