---

- name: Install asdf-vm
  git: 
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: "{{ asdf_version }}"

- name: List plugins
  shell: |
    source ~/.config/zsh/.zshrc
    asdf plugin list
  args:
    executable: /bin/zsh
  register: asdf_plugin_list
  changed_when: false
  ignore_errors: true

- name: Install some runtimes with asdf-vm
  shell: |
    source ~/.config/zsh/.zshrc
    asdf plugin add {{ item }}
  args:
    executable: /bin/zsh
  when: asdf_plugin_list.stdout.find(item) == -1
  with_items: "{{ asdf_plugins }}"