---
dotfiles:
  - path: ~/dotfiles/zsh/.zshenv
    dest: ~/.zshenv
  - path: ~/dotfiles/zsh/.zshrc
    dest: ~/.config/zsh/.zshrc
  - path: ~/dotfiles/zsh/zplug.zsh
    dest: ~/.config/zsh/zplug.zsh
  - path: ~/dotfiles/nvim/init.vim
    dest: ~/.config/nvim/init.vim
  # - path: ~/dotfiles/vscode/settings.json
  #   dest: ~/Library/Application Support/Code/User/settings.json
  # - path: ~/dotfiles/vscode/locale.json
  #   dest: ~/Library/Application Support/Code/User/locale.json

asdf_version: v0.7.8
asdf_plugins:
  - name: java
  - name: nodejs
    post_add: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  - name: python
    version: 3.8.1
    post_install: python -m pip install setuptools

vscode_files:
  - path: ~/dotfiles/vscode/settings.json
    dest: ~/Library/Application Support/Code/User/settings.json
  - path: ~/dotfiles/vscode/keybindings.json
    dest: ~/Library/Application Support/Code/User/keybindings.json
