---
- name: Include install task for RHEL
  include_tasks: rhel.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include install task for Debian
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure ~/.local/share/nvim/site/autoload exists
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
    mode: 0755
    recurse: yes

- name: Install nvim extension
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install nvim dependencies (only Debian)
  apt:
    name: python3-setuptools
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Check pynvim is installed
  shell: pip3 list --user | grep 'pynvim'; echo $?
  register: pynvim_install_result
  changed_when: false

- name: Check pynvim needs upgrade
  shell: pip3 list --outdated --user | grep 'pynvim'; echo $?
  register: pynvim_upgrade_result
  changed_when: false

- name: Install pynvim
  pip:
    name: pynvim
    extra_args: '--user --upgrade'
  changed_when: pynvim_install_result.stdout == "1" or pynvim_upgrade_result.stdout.find("\n0") != -1

