---
- name: Install nvim dependencies (only RedHat)
  yum:
    name: ["python-pip", "fuse-libs"]
  become: true

- name: Pre check neovim (only RedHat)
  stat:
    path: /usr/local/bin/nvim
  register: neovim_stats

- name: Install neovim (only RedHat)
  block:
    - name: Get neovim (only RedHat)
      get_url:
        url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
        dest: /tmp/nvim.appimage
        mode: 0755

    - name: Extract and move app image (only RedHat)
      shell: |
        ./nvim.appimage --appimage-extract
        mv squashfs-root /opt/nvim
      args:
        chdir: /tmp

    - name: Symlink neovim (only RedHat)
      file:
        src: /opt/nvim/AppRun
        dest: /usr/local/bin/nvim
        state: link
        force: yes
  when: not neovim_stats.stat.exists
  become: true
