---
- name: Remove apt cache workaround
  shell: rm -rf /var/lib/apt/lists/*
  when: ansible_distribution_major_version == '20'
  become: true

- name: Add neovim repository (only Debian)
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Install neovim (only Debian)
  apt:
    name: neovim
  become: true

- name: Symlink neovim (only Debian)
  file:
    src: /usr/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
    force: yes
  become: true
