---
- name: Check user directories
  stat:
    path: "{{ item }}"
  register: directory_stats
  with_items: "{{ dotfiles_directories|default([]) }}"

- name: Create multiple directories without disturbing previous permissions
  file:
    path: "{{ item.item }}"
    state: directory
  when: item.stat.exists == false
  with_items:
    - "{{ directory_stats.results }}"

- name: Symlink dotfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ dotfiles|default([]) }}"
  when: item.path is defined and item.dest is defined and item != ''

- name: Get git config
  shell: git config --list
  register: git_config
  changed_when: false

- name: Set global git config
  shell: git config --global {{ item.name }} {{ item.value }}
  when: git_config.stdout.find(item.name) == -1
  with_items:
    - name: user.name
      value: Shoma Nishitateno
    - name: push.default
      value: current
