- name: Get shell list
  shell: cat /etc/shells
  register: etc_shells

- name: Add `/etc/shells`
  lineinfile:
    dest: /etc/shells
    line: "{{ item }}"
    state: present
    owner: root
    group: wheel
    mode: 0644
  become: true
  when: etc_shells.stdout.find(item) == -1
  with_items:
    - /bin/zsh

- name: Change default shell
  shell: chsh -s /bin/zsh
  when: etc_shells.stdout.find('/bin/zsh') == -1
