- hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Add external apt repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items: "{{ apt_repositories|default([]) }}"
      when: item is defined and item != ''

    - name: Update apt-cache
      apt: update_cache=yes
      become: true

    - name: Install and upgrade apt packages
      apt:
        name: "{{ item.name|default(item) }}"
        state: "{{ item.state|default('latest') }}"
      with_items: "{{ apt_packages|default([]) }}"
      when: item is defined and item != ''
      become: true
  roles:
    - dotfiles
    - asdf
  vars:
    apt_packages:
      - zsh
