- hosts: localhost
  connection: local
  roles:
    - homebrew
    - dotfiles
    - asdf
    - vscode
    - nvim
  vars:
    vscode_extensions:
      - dbaeumer.vscode-eslint
      - eamodio.gitlens
      - esbenp.prettier-vscode
      - humao.rest-client
      - ms-azuretools.vscode-docker
      - ms-python.python
      - ms-vsliveshare.vsliveshare-pack
      - mtxr.sqltools
      - scalameta.metals
      - trinm1709.dracula-theme-from-intellij
      - vscodevim.vim
      - ms-vscode-remote.vscode-remote-extensionpack
