- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - apt
    - dotfiles
  vars:
    dotfiles:
      - path: ~/dotfiles/zsh/.zshenv
        dest: ~/.zshenv
      - path: ~/dotfiles/zsh/.zshrc
        dest: ~/.config/zsh/.zshrc
      # - path: ~/dotfiles/zsh/zplug.zsh
      #   dest: ~/.config/zsh/zplug.zsh
  tasks:
    - name: Add external apt repositories
      apt_repository: repo={{ item }} state=present
      with_items: "{{ apt_repositories|default([]) }}"
      when: item is defined and item != ''

    - name: Update apt-cache
      apt: update_cache=yes

    - name: Install/Upgrade apt packages
      apt: >
        name={{ item.name|default(item) }}
        state={{ item.state|default('latest') }}
      with_items: "{{ apt_packages|default([]) }}"
      when: item is defined and item != ''
