- hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Add external apt repositories
      apt_repository: repo={{ item }} state=present
      with_items: "{{ apt_repositories|default([]) }}"
      when: item is defined and item != ''

    - name: Update apt-cache
      apt: update_cache=yes
      become: true

    - name: Install and upgrade apt packages
      apt:
        name: "{{ item.name|default(item) }}"
        state: "{{ item.state|default('latest') }}"
      with_items: "{{ apt_packages|default([]) }}"
      when: item is defined and item != ''
      become: true
  roles:
    - dotfiles
    - asdf
  tasks:
    - name: Ensure /usr/local/opt directory exists
      file: 
        path: /usr/local/opt
        state: directory
      become: true

    - name: Check zplug is installed
      stat:
        path: /usr/local/opt/zplug
      register: zplug_exists

    - name: Install zplug
      git: 
        repo: https://github.com/zplug/zplug
        dest: /usr/local/opt/zplug
      become: true

  vars:
    apt_packages: []
  
