- hosts: localhost
  connection: local
  roles:
    - role: homebrew
      when: ansible_facts['os_family'] == "Darwin"
    - role: macos
      when: ansible_facts['os_family'] == "Darwin"
    - role: apt
      when: ansible_facts['os_family'] == "Debian"
    - role: dnf
      when: ansible_facts['os_family'] == "RedHat"
    - role: zsh
    - role: dotfiles
    - role: asdf
    - role: nvim
    - role: tmux
    - role: tig
  vars:
    apt_packages:
      - curl
      - zsh
      - gcc
      - make
      - zlib1g-dev
      - libbz2-dev
      - libssl-dev
      - libsqlite3-dev
      - libreadline-dev
      - libffi-dev
      - jq
      - silversearcher-ag
      - tig
      - tmux
    dnf_packages:
      - zsh
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - jq
      - the_silver_searcher
      - tig
      - tmux
      - wget
    dotfiles_directories:
      - ~/.config
      - ~/.cache
      - ~/.local
      - ~/.local/share
      - ~/.config/zsh
      - ~/.config/nvim
      - ~/.config/nvim/plugins
      - ~/.config/karabiner
      - ~/.config/tmux
      - ~/.config/tig
    dotfiles:
      - path: ~/dotfiles/zsh/.zshenv
        dest: ~/.zshenv
      - path: ~/dotfiles/zsh/.zshrc
        dest: ~/.config/zsh/.zshrc
      - path: ~/dotfiles/zsh/zinit.zsh
        dest: ~/.config/zsh/zinit.zsh
      - path: ~/dotfiles/nvim/init.vim
        dest: ~/.config/nvim/init.vim
      - path: ~/dotfiles/nvim/coc-settings.json
        dest: ~/.config/nvim/coc-settings.json
      - path: ~/dotfiles/nvim/plugins
        dest: ~/.config/nvim/plugins
      - path: ~/dotfiles/karabiner
        dest: ~/.config/karabiner
      - path: ~/dotfiles/tmux/tmux.conf
        dest: ~/.config/tmux/tmux.conf
      - path: ~/dotfiles/tig/.tigrc
        dest: ~/.config/tig/.tigrc
      - path: ~/dotfiles/intellij/.ideavimrc
        dest: ~/.ideavimrc
    asdf_version: v0.11.1
    asdf_plugins:
      - name: java
        version: zulu-11.54.23
      - name: nodejs
        version: 16.13.2
        # post_add: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
      - name: python
        version: 3.10.0
    macos_settings: []
