---
- name: Add external apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ apt_repositories|default([]) }}"
  when: item is defined and item != ''
  become: true

- name: Install and upgrade apt packages
  apt:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('latest') }}"
  with_items: "{{ apt_packages|default([]) }}"
  when: item is defined and item != ''
  become: true

- name: Install and upgrade snap packages
  snap:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    classic: yes
  with_items: "{{ snap_packages|default([]) }}"
  when: item is defined and item != ''
  become: true

# bat (ubuntu 18)
- name: Check bat is installed
  shell: which bat; echo $?
  register: bat_result
  changed_when: false

- name: Download bat 
  get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.16.0/bat-musl_0.16.0_amd64.deb 
    dest: /tmp/bat.deb
  when: "bat_result.stdout == '1'"

- name: Install bat 
  shell: dpkg -i /tmp/bat.deb
  when: "bat_result.stdout == '1'"
  become: true  

# fzf (ubuntu 18)
- name: Check fzf is installed
  shell: which fzf; echo $?
  register: fzf_result
  changed_when: false

- name: Download fzf 
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /tmp/fzf
    depth: 1
  when: "fzf_result.stdout == '1'"

- name: Install fzf
  shell: /tmp/fzf/install
  when: "fzf_result.stdout == '1'"
  become: true  

