name: CentOS

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install goss
        run: curl -fsSL https://goss.rocks/install | sudo sh

      - name: Provision
        run: |
          cd test
          make centos7
