name: CentOS

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: curl -sS https://raw.githubusercontent.com/shomatan/dotfiles/master/install.sh | bash

      - name: Install goss
        run: curl -fsSL https://goss.rocks/install | sudo sh
