name: ubuntu

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        env:
          CI: true
        run: curl -sS https://raw.githubusercontent.com/shomatan/dotfiles/master/tools/install.sh | bash
