name: Ubuntu

on: push

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install goss
        run: curl -fsSL https://goss.rocks/install | sudo sh

#      - name: Provision
#        run: ./install.sh
