name: ubuntu

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install goss
        run: curl -fsSL https://goss.rocks/install | sudo sh

      - name: Provision
        run: curl -sS https://raw.githubusercontent.com/shomatan/dotfiles/master/install.sh | bash
