name: Ubuntu

on: push

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3

      - run: curl -sS https://raw.githubusercontent.com/shomatan/dotfiles/master/install.sh | bash

      - name: Install goss
        run: curl -fsSL https://goss.rocks/install | sudo sh
